
/**
* arytmetyka.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Arytmetyka.idl
* œroda, 10 czerwca 2020 01:47:38 CEST
*/

public interface arytmetyka extends arytmetykaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface arytmetyka
